#!/bin/bash

progress-bar() {
  local current=$1
  local len=$2

  local bar_char='|'
  local empty_char=' '
  local length=50

  local perc_done=$((current * 100 /len))
  local num_bars=$((perc_done * length / 100))

  # echo "proccessing $current/$len ($perc_done%)"

  local i
  local s='['
  for ((i = 0; i < num_bars; i++)); do
        s+=$bar_char
  done
  for ((i = num_bars; i < length; i++)); do
        s+=$empty_char
  done
  s+=']'

  echo -ne "$s $current/$len ($perc_done%)\r"
}


proccess-file() {
  local file=$1

  sleep 0.1
}

echo 'finding files'

files=(./**/*cache)
len=${#files[@]}

echo "find $len files"

i=0

for file in "${files[@]}"; do
  progress-bar "$((i+1))" "$len"
  proccess-file = "$file"
  # echo "$file"
  ((i++))
done

echo